{{- if and (.Values.autoscaling.enabled) (.Capabilities.APIVersions.Has "keda.sh/v1alpha1") }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "this.fullname" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: organizationURL
      name: {{ include "this.fullname" . }}
      key: url
    - parameter: personalAccessToken
      name: {{ include "this.fullname" . }}
      key: pat
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "this.fullname" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: {{ include "this.fullname" . }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas | required "A value for .Values.autoscaling.maxReplicas is required" }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas | required "A value for .Values.autoscaling.minReplicas is required" }}
  pollingInterval: 5
  cooldownPeriod: {{ .Values.autoscaling.cooldown | required "A value for .Values.autoscaling.cooldown is required" }}
  triggers:
    - type: azure-pipelines
      metadata:
        poolName: {{ .Values.pipelines.pool | required "A value for .Values.pipelines.pool is required" }}
        demands: {{ join "," .Values.pipelines.capabiliies | default "" }}
        parent: {{ include "this.fullname" . }}-0
      authenticationRef:
        name: {{ include "this.fullname" . }}
{{- end }}
