{{- if and (.Values.autoscaling.enabled) (.Capabilities.APIVersions.Has "keda.sh/v1alpha1") }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "this.fullname" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: organizationURL
      name: {{ include "this.fullname" . }}
      key: url
    - parameter: personalAccessToken
      name: {{ include "this.fullname" . }}
      key: pat
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "this.fullname" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  jobTargetRef:
    parallelism: 1
    activeDeadlineSeconds: {{ .Values.pipelines.timeout | int | required "A value for .Values.pipelines.timeout is required" }}
    template:
      metadata:
        labels:
          {{- include "this.labels" . | nindent 10 }}
        annotations:
          # Cluster autoscaler never evicts this Pod
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          {{- with .Values.annotations }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        # The job cannot crash, this is not functionally intended; a shutdown is functionally a pipeline end
        restartPolicy: Never
        {{- include "this.podSharedTemplate" . | nindent 8 }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas | int | required "A value for .Values.autoscaling.maxReplicas is required" }}
  minReplicaCount: 0
  pollingInterval: 15
  rollout:
    # Do not delete executed jobs during upgrade
    strategy: gradual
  scalingStrategy:
    strategy: accurate
  triggers:
    - type: azure-pipelines
      metadata:
        poolName: {{ .Values.pipelines.pool | quote | required "A value for .Values.pipelines.pool is required" }}
        parent: {{ include "this.fullname" . }}-template
      authenticationRef:
        name: {{ include "this.fullname" . }}
{{- end }}
