{{- if .Values.autoscaling.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "this.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
  annotations:
    # Cluster autoscaler never evicts this Pod
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # This agent is a template, we privilegiate Jobs instead of it, but we need to run it first
  restartPolicy: Never
  {{- include "this.podSharedTemplate" . | nindent 2 }}
{{- end }}
