apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "azure-pipelines-agent.fullname" . }}
  labels:
    {{- include "azure-pipelines-agent.labels" . | nindent 4 }}
stringData:
  pat: {{ .Values.pipelines.pat | quote | required "A value for .Values.pipelines.pat is required" }}
  url: {{ .Values.pipelines.url | quote | required "A value for .Values.pipelines.url is required" }}
