apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "this.fullname" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
stringData:
  pat: {{ .Values.pipelines.pat | quote }}
  url: {{ .Values.pipelines.url | quote }}
