pipelines:
  pat: ojemi3pd7adocbqeeuzr5o7ldz2jlwxxbmtrrj7gq5mifhmafpsa
  pool: onprem_aks
  url: https://dev.azure.com/shopping-cart-devops-demo
  cacheType: azurefile-csi
  capabilities:
    - arch_arm64

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - arm64
