pipelines:
  pat: ojemi3pd7adocbqeeuzr5o7ldz2jlwxxbmtrrj7gq5mifhmafpsa
  pool: Kubernetes
  url: https://dev.azure.com/shopping-cart-devops-demo
  cacheType: azurefile-csi
  capabiliies:
    - arch-amd64

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - amd64
