apiVersion: v2
name: azure-pipelines-agent
description: Deploy Azure Pipelines agent on Kubernetes. Easy way.
type: application
# Using ephemeral storage, as from Kubernetes 1.19+ (alpha)
kubeVersion: ">=1.19"
version: 0.0.0
appVersion: 0.0.0
icon: https://raw.githubusercontent.com/clemlesne/azure-pipelines-agent/master/logo-1024.png
keywords:
  - agent
  - auto-scale
  - azure
  - azure-devops
  - azure-pipelines
  - container
  - devops
  - docker
  - helm
  - keda
  - kubernetes
  - pipelines
  - self-hosted
  - self-hosted-agent
home: https://github.com/clemlesne/azure-pipelines-agent
sources:
  - https://github.com/clemlesne/azure-pipelines-agent
maintainers:
  - name: Clémence Lesné
    email: clemence@lesne.pro
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
