version: 2
updates:
  - package-ecosystem: github-actions
    directory: ""
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: src/docker
    schedule:
      interval: daily
  - package-ecosystem: gitsubmodule
    schedule:
      interval: daily
    directory: cicd/version
