{{- if .Values.autoscaling.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "blue-agent.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "blue-agent.labels" . | nindent 4 }}
  annotations:
    # Cluster autoscaler never evicts this Pod
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- $data := dict
    "restartPolicy" "Never"
    "azpAgentName" (dict "value" (printf "%s-%s" (include "blue-agent.fullname" .) "template"))
  }}
  {{- include "blue-agent.podSharedTemplate" (merge (dict "Args" $data) . ) | nindent 2 }}
{{- end }}
