affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - arm64

pipelines:
  capabilities:
    - arch_arm64
  personalAccessToken: your-pat
  poolName: private_kube
  organizationURL: https://dev.azure.com/shopping-cart-devops-demo
