pipelines:
  pat: your-pat
  pool: private_kube
  url: https://dev.azure.com/shopping-cart-devops-demo
  cacheType: azurefile-csi
  capabilities:
    - ml_training

resources:
  limits:
    cpu: 8
    memory: 32Gi
  requests:
    cpu: 4
    memory: 16Gi

extraNodeSelectors:
  kubernetes.azure.com/agentpool: highperf
