pipelines:
  pat: your-pat
  pool: private_kube
  url: https://dev.azure.com/shopping-cart-devops-demo
  cache:
    type: managed-csi-premium
  capabilities:
    - ml_training

resources:
  limits:
    cpu: 8
    memory: 32Gi
  requests:
    cpu: 4
    memory: 16Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
              - highperf
